
modules:
  - name: TEKSI Wastewater
    id: tww
    organisation: teksi
    repository: wastewater
    exclude_releases: "plugin-ili-*"  # Example: exclude all v0.x releases

  - name: TEKSI District Heating
    id: tdh
    organisation: teksi
    repository: district_heating

  - name: TEKSI Cemetery
    id: tce
    organisation: teksi
    repository: cemetery
    experimental: true

  - name: SIGNALO
    id: signalo
    organisation: opengisch
    repository: signalo
