
modules:
  - name: TEKSI Wastewater
    organisation: teksi
    repository: wastewater

  - name: TEKSI District Heating
    id: tdh
    organisation: teksi
    repository: district_heating

  - name: TEKSI Cemetery
    id: tcm
    organisation: teksi
    repository: cemetery

  - name: SIGNALO
    organisation: opengisch
    repository: signalo
