
modules:
  - name: TEKSI Wastewater
    organisation: teksi
    repository: wastewater

  - name: TEKSI District Heating
    organisation: teksi
    repository: district_heating

  - name: TEKSI Cemetery
    organisation: teksi
    repository: cemetery

  - name: SIGNALO
    organisation: opengisch
    repository: signalo
